version: '3.8'
services:
  my-app-dockerfile:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CUSTOM_NAME=my-app-dockerfile
    ports:
      - "5051:8080"

  my-app-image:
    image: docker-app
    environment:
      - CUSTOM_NAME=my-app-image
    ports:
      - "5052:8080"
